import type { Metadata } from "next";
import { geistMono, geistSans } from "./fonts";
import "./globals.css";
import { Providers } from "./componentes/SnackProvider";
import ClientLayout from "./componentes/ClienteLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ margin: 0, padding: 0 }}
      >
        <Providers>
            <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
